version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: apps/contestapp/Dockerfile
    platform: linux/amd64
    ports:
      - "4200:80"
    image: 288694859166.dkr.ecr.eu-north-1.amazonaws.com/contestapp-frontend
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    platform: linux/amd64
    image: 288694859166.dkr.ecr.eu-north-1.amazonaws.com/contestapp-backend
    networks:
      - appnet
    ports:
      - "3000:3000"
networks:
  appnet:
