version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: apps/contestapp/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
